### ISSUE TITLE
Hybrid app or Native ?

### ISSUE THREAD

**Issue by wilsonpinto** [RefugeesWork/mobile-app#1]
Let's choose here.

I vote hybrid app (Cordova + ionic).
Simple, fast and multiplatform. [Showcase here](http://showcase.ionicframework.com/).

**Comment by serapath** [comment]
I'm all in on cordova - never used ionic and rather go browserify+npm, but who cares :-)

**Comment by wilsonpinto** [comment]
@serapath yea, cordova it's great. Maybe in future if application grows we can move to native, but for while we can make a good prototype of it.

**Comment by wilsonpinto** [comment]
if none disagree, i will start cordova/ionic tomorrow.

**Comment by serapath** [comment]
:+1:
